# **This a notebook on the k13_non_validated mutations observed**

In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import geopandas as gpd
from matplotlib.patches import Wedge

In [61]:
df=pd.read_excel('../data/cleaned_k13_2_latest.xlsx')
df

,pmid,year_pub,year_sample,country,region/province,town,participants_age,participants_age_unit,sample_size,first_line_act,...,type_of_mutation,mutation_frequency(%),where_sequenced,other_k13_mutations,data_extraction_comments,journal_access,raw_count,percentage_frequency,Latitude,Longitude
0,34551228,2021,2015-2019,UGANDA,NORTHERN UGANDA,GULU,≥0.5,YEARS,274,AL,...,NON-SYNONYMOUS,27,MISSING,-,RAW_COUNTS,OPEN,27.0,11.25,1.28,32.390
1,34551228,2021,2015-2029,UGANDA,NORTHERN UGANDA,GULU,≥0.5,YEARS,274,AL,...,NON-SYNONYMOUS,5,MISSING,-,RAW_COUNTS,OPEN,5.0,2.08,1.28,32.390
2,35703955,2022,missing,DRC,CENTRAL DRC,KINSHASHA,03-Jun,YEARS,118,ASAQ,...,MISSING,0,MISSING,"A578S, Q613E, S522C",RAW_COUNTS,OPEN,0.0,0.00,-2.88,23.656
3,36036611,2022,2016-2017,KENYA,WESTERN KENYA,SIAYA,<5,YEARS,340,AL,...,MISSING,0,MISSING,-,RAW_COUNTS,OPEN,0.0,0.00,1.00,37.906
4,39136468,2024,2015-2023,UGANDA,EASTERN UGANDA,"TORORO, BUSIA, MBALE",>0.5,YEARS,1112,AL,...,NON-SYNONYMOUS,4,MISSING,A578S,RAW_COUNTS,OPEN,4.0,0.36,1.28,32.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,37611122,2023,2022,UGANDA,RUKIGA,RUKIGA,missing,-,100,AL,...,NON-SYNONYMOUS,5.1,MISSING,-,PERCENTAGE,OPEN,3.0,5.10,1.28,32.390
661,37611122,2023,2022,UGANDA,RUKIGA,RUKIGA,missing,-,100,AL,...,NON-SYNONYMOUS,22.6,MISSING,-,PERCENTAGE,OPEN,12.0,22.60,1.28,32.390
662,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,9.8,MISSING,-,PERCENTAGE,OPEN,5.0,9.80,1.28,32.390
663,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,15.8,MISSING,-,PERCENTAGE,OPEN,9.0,15.80,1.28,32.390
664,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,0,MISSING,-,PERCENTAGE,OPEN,0.0,0.00,1.28,32.390

In [64]:
matched_pmids = []
target_mutations=["F446I",'N458Y','C469Y','M476I','R539T','Y493H','I543T','P553L','R561H','P574L','C580Y','R622I','A675V']
for i, mutations in enumerate(df["other_k13_mutations"].astype(str).tolist()):
    for mutation in target_mutations:
        if mutation in mutations:
            matched_pmids.append(df.loc[i, "pmid"])
            break  # Stop after the first match for this row

# Output the result
print(matched_pmids)

['36894982', '10.1101/2021.01.27.428390', 37611122, 37611122, 37611122]

In [65]:
matched_pmids = []
target_mutations = ["F446I", "N458Y", "C469Y", "M476I", "R539T", "Y493H", "I543T", "P553L", "R561H", "P574L", "C580Y", "R622I", "A675V"]

for i, mutations in enumerate(df["other_k13_mutations"].astype(str).tolist()):
    for mutation in target_mutations:
        if mutation in mutations:
            matched_pmids.append((df.loc[i, "pmid"], mutation))
            break  # Stop after the first match for this row

# Output the result
for pmid, mutation in matched_pmids:
    print(f"{pmid}: {mutation}")

36894982: N458Y
10.1101/2021.01.27.428390: M476I
37611122: R539T
37611122: R539T
37611122: R539T

In [57]:
df["other_k13_mutations"] = df["other_k13_mutations"].replace("-", np.nan)
df

,pmid,year_pub,year_sample,country,region/province,town,participants_age,participants_age_unit,sample_size,first_line_act,...,type_of_mutation,mutation_frequency(%),where_sequenced,other_k13_mutations,data_extraction_comments,journal_access,raw_count,percentage_frequency,Latitude,Longitude
0,34551228,2021,2015-2019,UGANDA,NORTHERN UGANDA,GULU,≥0.5,YEARS,274,AL,...,NON-SYNONYMOUS,27,MISSING,NaN,RAW_COUNTS,OPEN,27.0,11.25,1.28,32.390
1,34551228,2021,2015-2029,UGANDA,NORTHERN UGANDA,GULU,≥0.5,YEARS,274,AL,...,NON-SYNONYMOUS,5,MISSING,NaN,RAW_COUNTS,OPEN,5.0,2.08,1.28,32.390
2,35703955,2022,missing,DRC,CENTRAL DRC,KINSHASHA,03-Jun,YEARS,118,ASAQ,...,MISSING,0,MISSING,"A578S, Q613E, S522C",RAW_COUNTS,OPEN,0.0,0.00,-2.88,23.656
3,36036611,2022,2016-2017,KENYA,WESTERN KENYA,SIAYA,<5,YEARS,340,AL,...,MISSING,0,MISSING,NaN,RAW_COUNTS,OPEN,0.0,0.00,1.00,37.906
4,39136468,2024,2015-2023,UGANDA,EASTERN UGANDA,"TORORO, BUSIA, MBALE",>0.5,YEARS,1112,AL,...,NON-SYNONYMOUS,4,MISSING,A578S,RAW_COUNTS,OPEN,4.0,0.36,1.28,32.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,37611122,2023,2022,UGANDA,RUKIGA,RUKIGA,missing,-,100,AL,...,NON-SYNONYMOUS,5.1,MISSING,NaN,PERCENTAGE,OPEN,3.0,5.10,1.28,32.390
661,37611122,2023,2022,UGANDA,RUKIGA,RUKIGA,missing,-,100,AL,...,NON-SYNONYMOUS,22.6,MISSING,NaN,PERCENTAGE,OPEN,12.0,22.60,1.28,32.390
662,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,9.8,MISSING,NaN,PERCENTAGE,OPEN,5.0,9.80,1.28,32.390
663,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,15.8,MISSING,NaN,PERCENTAGE,OPEN,9.0,15.80,1.28,32.390
664,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,0,MISSING,NaN,PERCENTAGE,OPEN,0.0,0.00,1.28,32.390

In [73]:
df_coordinates = df[["country", "region/province"]].drop_duplicates().reset_index(drop=True)
df_coordinates= df_coordinates.sort_values(by='country').reset_index(drop=True)
df_coordinates.to_excel("../data/cordinates.xlsx", index=False)
df_coordinates

      country                                    region/province
0     BURUNDI                                            MISSING
1         DRC                                           NORTHERN
2         DRC                                          SOUNTHERN
3         DRC                                                  -
4         DRC                                                DRC
..        ...                                                ...
122    UGANDA                                    NORTHERN-UGANDA
123    UGANDA                                    TORORO DISTRICT
124    UGANDA                         TORORO, JINJA, AND KANUNGU
125    UGANDA                                              LAMWO
126  ZANZIBAR  UGUNJA & PEMBAMICHEWENI,CHAKE,MKOANI,MAGHARIBI...

[127 rows x 2 columns]

In [59]:
df_other=pd.DataFrame()
for i, mutations in enumerate(df["other_k13_mutations"].astype(str).tolist()):
    print(df.loc[i, "pmid"], mutations)
    df_other=pd.DataFrame(columns=df.loc())

34551228 nan
34551228 nan
 35703955 A578S, Q613E, S522C
36036611 nan
39136468 A578S
39136468 nan
34641867 TGC469TGT, GGC548GGT
26483118 nan
26483118 nan
26483118 nan
26483118 nan
26483118 nan
36451216 E433D
36451216 nan
29718283 nan
39159629 R255K, L258M
39159629 nan
39159629 nan
39159629 R255K, L258M, K189T
39159629 nan
39159629 nan
39159629 A175T, A578S, R255K, N133K, N137D, N137K, N217H, N264S, Q271L, E208K, G112E, H384R, I205T, L116I, L258M, K189N, K189T, F699C, P419S, P667S, S182T, T149S, T207K
39159629 nan
39159629 nan
39159629 R255K, L258M, K189T
39159629 nan
39159629 nan
39159629 R255K, L258M, K108E, K189T
39159629 nan
39159629 nan
39159629 R255k, H136N, L258M, K189T
39159629 nan
39159629 nan
39159629 A578S, R255K, N133K, N137D, N137K, N217H, N264S, Q271L, G112E, H136N, L116I, L177I, L258M, L99V, K108E, K124N, K189N, K189T, S182, T149T, T207K, T348I, V555A
39159629 nan
39159629 nan
39159629 A578S, R255K, L258M
39159629 nan
39159629 nan
39159629 R255K, H136N, L258M, K189T, K9R, P667T, S182T
39159629 nan
39159629 nan
39159629 R255K, N217H, L258M, K189N, K189T
39159629 nan
39159629 nan
39159629 A578S, R255K, H384R, L258M, K189T, S182T, T149S
39159629 nan
39159629 nan
39159629 A578S, R255K, N133K, N137D, N137K, N217H, N264S, H136N, I205T, L116I, L258M, L99V, K124N, K189N, K189T, P419S, S182T, T149S
39159629 nan
39159629 nan
39159629 R255K, H136N, K189T
39159629 nan
39159629 nan
34615917 nan
38712186 A569S, A578S,F491S
38712186 nan
34152946 P417P,R471R,S477S,T478T,A504A,S576S,S477Y,A578Y
34152946 P417P, V454V,C469C,R471R,A504A,G533G,S522C,A578Y
34152946 P417P,C469C,R471R,V487V,R539R,I416V,E433D,R471S,A578Y,Q613E
31034031 A621V
30898164 R471S,A578S,E433D,I416V,Q613E
32795367 S522C, A578S
35266823 A569S, A578S
31358588 K610E, P615N
31358588 nan
31358588 V555A, A578S, N594K, L618S
31358588 W470R, A578S
31358588 V581I
31358588 K563E, A578S
31358588 V555A
31358588 S522C, A578S
31358588 nan
31358588 I540T, G533A, V555A
31358588 G496S, V555A, E567K, A578S
31358588 nan
31358588 nan
31358588 L457I, W565R
31358588 I465T, L619S, C469F, M472V, Y558H, A569T, A569S, A578S, N594K, A617T
35511795 E596V,E643K,S600C,A578S,I587I,Y588N
26801909 A578S, P553P
26392510 nan
25695257 M442V, N554S, A569S, A578S, C439C, S477S, Y500Y, N531N, G538G
38746440 441L, 449A, 469F, 568G
38746440 nan
38746440 nan
38746440 441L, 469F
38746440 nan
38746440 nan
38746440 nan
38746440 441L, 469F
38746440 568G
34491220 P417P, C469C, R471R, S477S, T478T, G496G, Y511Y, R539R, S576S, S477Y
34491220 nan
34491220 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
33146722 nan
25144768 K189T,K189N,F334L,L368L,F439F,I465T,Q467Q,S522S,Y558H,A578S,A617T,L619S,V637D
33350925 C469F,G533A,V555A,A578S
33350925 nan
27573632 nan
27573632 nan
27573632 V555A, A626S, D648H
27573632 nan
34270452 A566C,G523A
32103124 A578S,A359T,A427S,C469C,G538G,I354V,I526I,P417P,S624S,V487V
28420403 D464N, R539R, S549P, L598L, E602E, K669K
28420403 S466I,Q467H,N489N,G496G,I552M,N609N,F628L,
32070355 F375S, K378R, D389N, K430K, E433D, P443P, N594K
39103358 A578S, V568I, I416V, H384Y, Y328F, L258M, R255K, K189T
38876161 P443S, S459, G496S, G497D, V520I, G591E, A676T, N689S, G690D
38840941 nan
38287365 G533G,P655P,G690G
38287365 G533G,G690G,A582V
38287365 T535T
38287365 I646L
38287365 G690G,A582V
38287365 G533G,H560H
38287365 nan
38287365 V637V,E643E,A578S,A582V
38287365 A569S,A578S,A582V,P667S
38287365 V637V,C469C,A578S
38287365 C469C,A578S
38287365 nan
38287365 nan
38287365 nan
38287365 nan
38287365 nan
38287365 A582V
38287365 nan
38287365 nan
38287365 nan
38287365 nan
38287365 nan
38287365 nan
37452073 A578S,F451Y
36894982 R539T,N458Y, N431S, A671V
36100912 nan
36100912 "504, 510"
33663492 K189T
31756512 W611S
29582728 S485K, N498I,  L505F,  W518C, R529K, N530K, V568G, A578S, N587K, A676V, T677K, T677R, T677S, L678V
29582728 A504G, L505F, E509G,N530Y,G592E,E596R,A676V,T677R,L678V
29582728 E509G, V568G, D584Y,N585K, T677R
29582728 A578S, N585K, N609L, A676V, T677R, L678V
29582728 E509G, N585K, Y616N, E620K, R622G
29582728 L505F, S522R, N530I, N531I, S536L, R539K, P570L, N585K, L598F, T677K, T677A
29582728 L505F,E509G, N585K
29582728 A578S, N585K
29363453 nan
29363453 T474T, A569S
29363453 nan
29363453 C469W, C469C, R513S, A578S, R597R
29363453 C469C
29363453 N490S
29363453 L457I, E507E, G548G, A578S
29363453 I448M, S522C, A554S, A578S, I590F, E612D
34908849 G1929A, A1788T, C1801G
34952573 nan
10.1186/s12936-021-04023-3 nan
36289202 G533A
36289202 nan
36289202 nan
36289202 nan
36289202 nan
36289202 nan
38352311 nan
38712186 A569S, A578S, F491S
38712186 nan
39028193 Y546H,A578S
39028193 A578S
39028193 nan
39028193 C469C, Y511H, G533A, A578S, G533G, V581A, I646I, V650I
39028193 Q654R
39028193 nan
39028193 P475S, E620K,
39028193 nan
39028193 A504A, V517V, L631F
39028193 E461G. G625R
39028193 nan
39028193 I448V, C469C, Y511H, R561R, A578S, Y630F
39028193 nan
34216470 C469F, Q661E, P667S
34216470 nan
30559133 A578S
30559133 nan
29553316 M472V, A621S, V666I
29553316 nan
28968782 A569T, G638R, N594K
28923866 A569T, G638R, N594K
28068997 A578S
28039354 V555A, M472V, A569S, K563E, A578S
27543172 E509E,S522R, G533C
26079933 A578S
39083679 T535A, A504T, Y630F, N599I, S550F
37640962 K189T, E401Q, E433D
31516103 nan
28746333 nan
39159633 nan
37170467 nan
31296223 nan
39159629 C469F, P667S, Q661E
39159629 nan
39159629 nan
38196592 F699C , R575K
38196592 nan
38196592 nan
38092677 578S,555A,C469F
38092677 nan
 37986920 nan
 37986920 nan
 37986920 nan
37096145 V555A , C532W, G533A
37754284 nan
37754284 nan
37754284 nan
37754284 nan
31369106 nan
39136465 nan
38461239 I416V, E433D, R471S, P475S, A578S, Q613E
28535801 S549P, P553P, A578S
38016502 Q613E, V637I,P441L
34694871 nan
35388682 nan
35388682 nan
35144535 A578S, M472L, D516A, V568M, S576T, D584E, Y588C
35051550 C532S , Q613E
33706773 nan
32822392 nan
30373565 A578S
28594879 F495L, S522C, V520A, M476K, N523T, E509D
39425178 nan
10.2139/ssrn.4938046 K189T, V714D, R716I, M18T, E401Q, H136N, N135H
29582728 S485K, N498I,L505F, W528C, R529K, N530K, V568G, A578S, N587K, A676V, T677K, T677R, T677S, L678V
29582728 A504G,L505F, E509G, N530Y, G592E, E596R, A676V, L678V
29582728 E509G, V568G, D584Y, D585K, T677R
29582728 A578S, N585K, N609L, A676V, T677R, L678V
29582728 E509G, N585K, Y616N, E620K, R622G
29582728 A578S, N585K
29582728 L505F, S522R, N530I, N531I, S536L, R539K, P570L, N585K, L598F, T677K, T677A,
29582728 L505F, E509G, N585K
34111412 D399N, A486S, C542R, G665S, A578S
25986047 N531I
37349311 nan
37349311 nan
37349311 nan
30898164 nan
30898164 R471S
30898164 A578S, E433D
30898164 I416V, Q613E
10.2139/SSRN.4617870 nan
10.2139/SSRN.4617870 nan
10.2139/SSRN.4617870 nan
10.2139/SSRN.4617870 nan
10.12688/wellcomeopenres.17656.1 I354V, A486S, V487A, S522C, A578S, A582V, S600A, I634L, V666L, A676S
10.1101/2021.01.27.428390 M460I, V487I, A578V, A626E, G592E+V637I
10.1101/2021.01.27.428390 C469F, R513L, A578S, P667R
10.1101/2021.01.27.428390 V555A, R575I, E605K, E651K
10.1101/2021.01.27.428390 nan
10.1101/2021.01.27.428390 L463S, M476I, G496S, V510M, E556K, M562T, E602D
10.1101/2021.01.27.428390 nan
10.1101/2021.01.27.428390 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
37640962 nan
38339833 nan
38339833 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 V666I
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 A724P
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 C469F
37611122 nan
37611122 nan
37611122 C469F,A578S,V517I
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 G533A, I540T
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 G533A, R539T, A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 C469F
37611122 nan
37611122 nan
37611122 P441L
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 C469F
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 C469F, F442L, I540T
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 C469F
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 G533A, A578S, K607E
37611122 nan
37611122 nan
37611122 R539T
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 R539T, V637I
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 F442L, K607E
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L, A578S
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 N490T
37611122 nan
37611122 nan
37611122 N490T
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 C469F
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441A, A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 N490T
37611122 nan
37611122 nan
37611122 Y558C, A578S
37611122 nan
37611122 nan
37611122 C469F, F442L, R575K, L713F
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L, Y558C, A724P
37611122 nan
37611122 nan
37611122 V517I, A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L, P667L, L713F
37611122 nan
37611122 nan
37611122 P441L, C469F
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441A, A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L, A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 S522C, A578S
37611122 nan
37611122 nan
37611122 P441A
37611122 nan
37611122 nan
37611122 P441L, N490T, V555A, L713F, A724P
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L, G533A, Y558C, A578S, P667S, F699C, A724P
37611122 nan
37611122 nan
37611122 R575K, V637I
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 S522C, A578S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 P441L, A569V, L713F
37611122 nan
37611122 nan
37611122 C469F, N490T, G718S
37611122 nan
37611122 nan
37611122 nan
37611122 nan
37611122 nan

In [10]:
df["other_k13_mutations"]=df["other_k13_mutations"].str.strip()
df
"""country_mut=df.pivot_table(
    index="country",
    columns="other_k13_mutations.str.strip()",
    aggfunc="count"
)
country_mut"""

'country_mut=df.pivot_table(\n    index="country",\n    columns="other_k13_mutations.str.strip()",\n    aggfunc="count"\n)\ncountry_mut'

In [16]:
df["other_k13_mutations"]

0                        -
1                        -
2      A578S, Q613E, S522C
3                        -
4                    A578S
              ...
660                      -
661                      -
662                      -
663                      -
664                      -
Name: other_k13_mutations, Length: 665, dtype: object

In [12]:
df_exploded = df.explode("other_k13_mutations")
df_exploded

,pmid,year_pub,year_sample,country,region/province,town,participants_age,participants_age_unit,sample_size,first_line_act,...,type_of_mutation,mutation_frequency(%),where_sequenced,other_k13_mutations,data_extraction_comments,journal_access,raw_count,percentage_frequency,Latitude,Longitude
0,34551228,2021,2015-2019,UGANDA,NORTHERN UGANDA,GULU,≥0.5,YEARS,274,AL,...,NON-SYNONYMOUS,27,MISSING,-,RAW_COUNTS,OPEN,27.0,11.25,1.28,32.390
1,34551228,2021,2015-2029,UGANDA,NORTHERN UGANDA,GULU,≥0.5,YEARS,274,AL,...,NON-SYNONYMOUS,5,MISSING,-,RAW_COUNTS,OPEN,5.0,2.08,1.28,32.390
2,35703955,2022,missing,DRC,CENTRAL DRC,KINSHASHA,03-Jun,YEARS,118,ASAQ,...,MISSING,0,MISSING,"A578S, Q613E, S522C",RAW_COUNTS,OPEN,0.0,0.00,-2.88,23.656
3,36036611,2022,2016-2017,KENYA,WESTERN KENYA,SIAYA,<5,YEARS,340,AL,...,MISSING,0,MISSING,-,RAW_COUNTS,OPEN,0.0,0.00,1.00,37.906
4,39136468,2024,2015-2023,UGANDA,EASTERN UGANDA,"TORORO, BUSIA, MBALE",>0.5,YEARS,1112,AL,...,NON-SYNONYMOUS,4,MISSING,A578S,RAW_COUNTS,OPEN,4.0,0.36,1.28,32.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,37611122,2023,2022,UGANDA,RUKIGA,RUKIGA,missing,-,100,AL,...,NON-SYNONYMOUS,5.1,MISSING,-,PERCENTAGE,OPEN,3.0,5.10,1.28,32.390
661,37611122,2023,2022,UGANDA,RUKIGA,RUKIGA,missing,-,100,AL,...,NON-SYNONYMOUS,22.6,MISSING,-,PERCENTAGE,OPEN,12.0,22.60,1.28,32.390
662,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,9.8,MISSING,-,PERCENTAGE,OPEN,5.0,9.80,1.28,32.390
663,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,15.8,MISSING,-,PERCENTAGE,OPEN,9.0,15.80,1.28,32.390
664,37611122,2023,2022,UGANDA,TORORO,TORORO,missing,-,100,AL,...,NON-SYNONYMOUS,0,MISSING,-,PERCENTAGE,OPEN,0.0,0.00,1.28,32.390

In [29]:
import pandas as pd
import ast

# Safely convert stringified lists into actual Python lists
df["other_k13_mutations"] = df["other_k13_mutations"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

# Collect rows
rows = []

for i, mutations in enumerate(df["other_k13_mutations"]):
    pmid = df.loc[i, "pmid"]
    if isinstance(mutations, list):
        for mut in mutations:
            rows.append({"pmid": pmid, "mutation": mut})
    else:
        rows.append({"pmid": pmid, "mutation": mutations})

# Now create the DataFrame
other_k13 = pd.DataFrame(rows)

# Optional: clean up mutation strings
other_k13["mutation"] = other_k13["mutation"].astype(str).str.strip()

SyntaxError: invalid syntax (<unknown>, line 1)

In [30]:
import pandas as pd
import ast

# Sample data setup (if needed)
# df = pd.DataFrame({
#     "pmid": [12345, 67890],
#     "other_k13_mutations": ["['C580Y', 'A578S']", "['R539T']"]
# })

# Convert stringified lists to actual lists (if needed)
df["other_k13_mutations"] = df["other_k13_mutations"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

# Build the rows
rows = []
for i, mutations in enumerate(df["other_k13_mutations"]):
    pmid = df.loc[i, "pmid"]
    if isinstance(mutations, list):
        for mut in mutations:
            rows.append({"pmid": pmid, "mutation": mut})
    else:
        rows.append({"pmid": pmid, "mutation": mutations})

# Create the new DataFrame
other_k13 = pd.DataFrame(rows)

# Optional: Clean mutation strings
other_k13["mutation"] = other_k13["mutation"].astype(str).str.strip()

# Display it
print(other_k13)

SyntaxError: invalid syntax (<unknown>, line 1)

In [31]:
ls

after_extraction.ipynb       Cleaneup_pubmed.ipynb       data_cleaning.ipynb
cleaned_googleScholar.ipynb  clean_google_scholar.ipynb  non_validated.ipynb